server.port=8085
spring.application.name=pago-service


spring.datasource.url=jdbc:oracle:thin:@ecommerce_high?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=PAGO_USER
spring.datasource.password=Pagosuser123

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

orden-service.url=http://localhost:8084/api/v1/ordenes
